use dashmap::DashMap;
use std::path::Path;
use std::sync::Arc;
use tokio::sync::{Mutex, mpsc};
use tokio_stream::wrappers::ReceiverStream;
use tonic::{Request, Response, Status, Streaming};

use arx_core::container::superblock::Superblock;
use arx_core::crud::CrudArchive;
use arx_core::crypto::kdf::derive_key;
use arx_core::error::ArxError;
use arx_core::read::extract::{ExtractOptions, verify};
use arx_core::repo::OpenParams;
use arx_core::repo_factory::{Backend, open_repo};
use arx_core::{ListOptions, PackOptions, pack};

use crate::arx::arx_service_server::ArxService;
use crate::arx::*;
use crate::auth::{check_admin, extract_bearer, extract_identity, extract_tenant, issue_jwt};
use crate::db::AuthDb;
use crate::store::ArchiveStore;

pub struct ArxServiceImpl {
    pub store: Arc<ArchiveStore>,
    pub db: Arc<AuthDb>,
    pub admin_key: Arc<String>,
    pub archive_locks: Arc<DashMap<String, Arc<Mutex<()>>>>,
}

impl ArxServiceImpl {
    fn archive_lock(&self, tenant_id: &str, archive_id: &str) -> Arc<Mutex<()>> {
        let key = format!("{tenant_id}:{archive_id}");
        self.archive_locks
            .entry(key)
            .or_insert_with(|| Arc::new(Mutex::new(())))
            .clone()
    }
}

/// Map ArxError to tonic Status.
fn arx_err(e: ArxError) -> Status {
    match e {
        ArxError::AeadError => Status::unauthenticated("AEAD authentication failed — wrong key"),
        ArxError::Io(_) => Status::internal("storage error"),
        ArxError::Format(msg) => Status::invalid_argument(msg),
    }
}

/// Resolve a raw 32-byte key from KeyMaterial + archive superblock (for password derivation).
fn resolve_key(archive_path: &Path, key: Option<&KeyMaterial>) -> Result<Option<[u8; 32]>, Status> {
    let Some(km) = key else { return Ok(None) };
    match &km.key_source {
        Some(key_material::KeySource::RawKey(bytes)) => {
            if bytes.len() != 32 {
                return Err(Status::invalid_argument("raw_key must be exactly 32 bytes"));
            }
            let mut arr = [0u8; 32];
            arr.copy_from_slice(bytes);
            Ok(Some(arr))
        }
        Some(key_material::KeySource::Password(pw)) => {
            // Read kdf_salt from the archive's superblock
            let mut f =
                std::fs::File::open(archive_path).map_err(|e| Status::internal(e.to_string()))?;
            let sb = Superblock::read_from(&mut f).map_err(|e| Status::internal(e.to_string()))?;
            Ok(Some(derive_key(pw, &sb.kdf_salt)))
        }
        None => Ok(None),
    }
}

/// Resolve a raw key without needing an archive path (for pack / issue where archive doesn't exist yet).
fn resolve_key_no_archive(key: Option<&KeyMaterial>) -> Result<Option<[u8; 32]>, Status> {
    let Some(km) = key else { return Ok(None) };
    match &km.key_source {
        Some(key_material::KeySource::RawKey(bytes)) => {
            if bytes.len() != 32 {
                return Err(Status::invalid_argument("raw_key must be exactly 32 bytes"));
            }
            let mut arr = [0u8; 32];
            arr.copy_from_slice(bytes);
            Ok(Some(arr))
        }
        Some(key_material::KeySource::Password(pw)) => {
            // For new archives, use password directly — kdf_salt is auto-generated by pack()
            // We store the password in PackOptions.password
            let _ = pw; // handled in PackOptions below
            Ok(None) // password passed through PackOptions.password
        }
        None => Ok(None),
    }
}

fn password_from_key(key: Option<&KeyMaterial>) -> Option<String> {
    key.and_then(|km| match &km.key_source {
        Some(key_material::KeySource::Password(pw)) => Some(pw.clone()),
        _ => None,
    })
}

#[tonic::async_trait]
impl ArxService for ArxServiceImpl {
    // ── PackStream ───────────────────────────────────────────────────────────
    async fn pack_stream(
        &self,
        request: Request<Streaming<UploadFrame>>,
    ) -> Result<Response<PackResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let mut stream = request.into_inner();

        // First frame must be PackHeader
        let first = stream
            .message()
            .await?
            .ok_or_else(|| Status::invalid_argument("empty upload stream"))?;
        let header = match first.payload {
            Some(upload_frame::Payload::PackHeader(h)) => h,
            _ => return Err(Status::invalid_argument("first frame must be PackHeader")),
        };

        let archive_id = self
            .store
            .new_archive(&tenant_id, &header.archive_name)
            .map_err(|e| Status::internal(e.to_string()))?;
        let paths = self.store.archive_paths(&tenant_id, &archive_id);

        // Write incoming files to a tempdir, then pack
        let tmp = tempfile::tempdir().map_err(|e| Status::internal(e.to_string()))?;
        let mut current_file: Option<(std::path::PathBuf, std::fs::File)> = None;

        while let Some(frame) = stream.message().await? {
            match frame.payload {
                Some(upload_frame::Payload::FileInfo(fi)) => {
                    if let Some((_, mut f)) = current_file.take() {
                        let _ = std::io::Write::flush(&mut f);
                    }
                    let dest = tmp.path().join(fi.path.trim_start_matches('/'));
                    if let Some(parent) = dest.parent() {
                        std::fs::create_dir_all(parent)
                            .map_err(|e| Status::internal(e.to_string()))?;
                    }
                    let f = std::fs::File::create(&dest)
                        .map_err(|e| Status::internal(e.to_string()))?;
                    current_file = Some((dest, f));
                }
                Some(upload_frame::Payload::Data(bytes)) => {
                    if let Some((_, ref mut f)) = current_file {
                        use std::io::Write;
                        f.write_all(&bytes)
                            .map_err(|e| Status::internal(e.to_string()))?;
                    }
                }
                Some(upload_frame::Payload::Finalize(_)) => break,
                _ => {}
            }
        }
        drop(current_file);

        let key = header.key.as_ref();
        let aead_key = resolve_key_no_archive(key)?;
        let password = password_from_key(key);

        let opts = PackOptions {
            deterministic: header.deterministic,
            min_gain: if header.min_gain > 0.0 {
                header.min_gain
            } else {
                0.05
            },
            aead_key,
            password,
            meta_label: if header.label.is_empty() {
                None
            } else {
                Some(header.label)
            },
            meta_owner: if header.owner.is_empty() {
                None
            } else {
                Some(header.owner)
            },
            meta_notes: if header.notes.is_empty() {
                None
            } else {
                Some(header.notes)
            },
            ..Default::default()
        };

        let input_path = tmp.path().to_path_buf();

        tokio::task::spawn_blocking({
            let out = paths.data.clone();
            move || {
                let refs = vec![input_path.as_path()];
                pack(&refs, &out, Some(&opts))
            }
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        Ok(Response::new(PackResponse {
            archive_id,
            stats: None,
            error: String::new(),
        }))
    }

    // ── List ─────────────────────────────────────────────────────────────────
    async fn list(&self, request: Request<ListRequest>) -> Result<Response<ListResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let opts = aead_key.map(|k| ListOptions {
            aead_key: Some(k),
            key_salt: [0u8; 32],
        });

        // Use the repo to get entries
        let params = OpenParams {
            archive_path: archive_path.clone(),
            aead_key: opts.as_ref().and_then(|o| o.aead_key),
            key_salt: [0u8; 32],
        };
        let repo = open_repo(Backend::Fs, params).map_err(arx_err)?;
        let files = repo.list_files().map_err(arx_err)?;

        let entries = files
            .into_iter()
            .map(|f| ListEntry {
                path: f.path,
                u_size: f.u_size,
                c_size: 0, // TODO: sum c_sizes from chunk_map
                chunks: f.chunks as u32,
            })
            .collect();

        Ok(Response::new(ListResponse { entries }))
    }

    // ── ExtractStream ────────────────────────────────────────────────────────
    type ExtractStreamStream = ReceiverStream<Result<DownloadFrame, Status>>;

    async fn extract_stream(
        &self,
        request: Request<ExtractRequest>,
    ) -> Result<Response<Self::ExtractStreamStream>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;

        let (tx, rx) = mpsc::channel(16);

        tokio::task::spawn_blocking(move || {
            let params = OpenParams {
                archive_path: archive_path.clone(),
                aead_key,
                key_salt: [0u8; 32],
            };
            let repo = match open_repo(Backend::Fs, params) {
                Ok(r) => r,
                Err(e) => {
                    let _ = tx.blocking_send(Err(arx_err(e)));
                    return;
                }
            };

            let files = match repo.list_files() {
                Ok(f) => f,
                Err(e) => {
                    let _ = tx.blocking_send(Err(arx_err(e)));
                    return;
                }
            };

            for file in files {
                if !req.path.is_empty() && file.path != req.path {
                    continue;
                }
                // Send file info frame
                let _ = tx.blocking_send(Ok(DownloadFrame {
                    payload: Some(download_frame::Payload::File(FileInfo {
                        path: file.path.clone(),
                        mode: 0o644,
                        mtime: 0,
                        size: file.u_size,
                    })),
                }));
                // Stream content
                let start = if req.path.is_empty() { 0 } else { req.start };
                let len = if req.len == 0 { u64::MAX / 4 } else { req.len };
                let mut reader = match repo.open_range(&file.path, start, len) {
                    Ok(r) => r,
                    Err(e) => {
                        let _ = tx.blocking_send(Err(arx_err(e)));
                        return;
                    }
                };
                let mut buf = vec![0u8; 512 * 1024];
                loop {
                    use std::io::Read;
                    let n = match reader.read(&mut buf) {
                        Ok(n) => n,
                        Err(e) => {
                            let _ = tx.blocking_send(Err(Status::internal(e.to_string())));
                            return;
                        }
                    };
                    if n == 0 {
                        break;
                    }
                    let _ = tx.blocking_send(Ok(DownloadFrame {
                        payload: Some(download_frame::Payload::Data(buf[..n].to_vec())),
                    }));
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    // ── Verify ───────────────────────────────────────────────────────────────
    async fn verify(
        &self,
        request: Request<VerifyRequest>,
    ) -> Result<Response<VerifyResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let opts = aead_key.map(|k| ExtractOptions {
            aead_key: Some(k),
            ..Default::default()
        });

        match tokio::task::spawn_blocking(move || verify(&archive_path, opts.as_ref()))
            .await
            .map_err(|e| Status::internal(e.to_string()))?
        {
            Ok(()) => Ok(Response::new(VerifyResponse {
                ok: true,
                error: String::new(),
            })),
            Err(e) => Ok(Response::new(VerifyResponse {
                ok: false,
                error: e.to_string(),
            })),
        }
    }

    // ── Issue ────────────────────────────────────────────────────────────────
    async fn issue(
        &self,
        request: Request<IssueRequest>,
    ) -> Result<Response<IssueResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let aead_key = resolve_key_no_archive(req.key.as_ref())?;

        let archive_id = self
            .store
            .new_archive(&tenant_id, &req.archive_name)
            .map_err(|e| Status::internal(e.to_string()))?;
        let paths = self.store.archive_paths(&tenant_id, &archive_id);

        let label = req.label.clone();
        let owner = req.owner.clone();
        let notes = req.notes.clone();
        let deterministic = req.deterministic;
        tokio::task::spawn_blocking(move || {
            CrudArchive::issue_archive(
                &paths.data,
                &label,
                &owner,
                &notes,
                aead_key,
                [0u8; 32],
                deterministic,
            )
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        // Persist the display name in the mutable sidecar so it survives
        // manifest regeneration during sync (and matches what the user sees
        // immediately after creation).
        let display_name = if !req.label.trim().is_empty() {
            req.label.trim().to_string()
        } else if !req.archive_name.trim().is_empty() {
            req.archive_name.trim().to_string()
        } else {
            String::new()
        };
        if !display_name.is_empty() {
            self.store
                .write_label(&tenant_id, &archive_id, &display_name)
                .map_err(|e| Status::internal(e.to_string()))?;
        }

        Ok(Response::new(IssueResponse {
            archive_id,
            error: String::new(),
        }))
    }

    // ── CrudAddStream ────────────────────────────────────────────────────────
    async fn crud_add_stream(
        &self,
        request: Request<Streaming<UploadFrame>>,
    ) -> Result<Response<CrudAddResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let mut stream = request.into_inner();

        let first = stream
            .message()
            .await?
            .ok_or_else(|| Status::invalid_argument("empty stream"))?;
        let header = match first.payload {
            Some(upload_frame::Payload::CrudHeader(h)) => h,
            _ => return Err(Status::invalid_argument("first frame must be CrudHeader")),
        };

        let archive_path = self.store.resolve(&tenant_id, &header.archive_id)?;
        let aead_key = resolve_key(&archive_path, header.key.as_ref())?;
        let _lock = self
            .archive_lock(&tenant_id, &header.archive_id)
            .lock_owned()
            .await;
        tracing::info!(tenant_id = %tenant_id, archive_id = %header.archive_id, "crud_add_stream");

        let tmp = tempfile::tempdir().map_err(|e| Status::internal(e.to_string()))?;
        let mut files: Vec<(String, std::path::PathBuf, u32, u64)> = Vec::new();
        let mut current: Option<(String, std::path::PathBuf, std::fs::File, u32, u64)> = None;

        while let Some(frame) = stream.message().await? {
            match frame.payload {
                Some(upload_frame::Payload::FileInfo(fi)) => {
                    if let Some((p, path, mut f, m, t)) = current.take() {
                        let _ = std::io::Write::flush(&mut f);
                        files.push((p, path, m, t));
                    }
                    let dest = tmp.path().join(fi.path.trim_start_matches('/'));
                    if let Some(par) = dest.parent() {
                        std::fs::create_dir_all(par)
                            .map_err(|e| Status::internal(e.to_string()))?;
                    }
                    let f = std::fs::File::create(&dest)
                        .map_err(|e| Status::internal(e.to_string()))?;
                    current = Some((fi.path, dest, f, fi.mode, fi.mtime as u64));
                }
                Some(upload_frame::Payload::Data(bytes)) => {
                    if let Some((_, _, ref mut f, _, _)) = current {
                        use std::io::Write;
                        f.write_all(&bytes)
                            .map_err(|e| Status::internal(e.to_string()))?;
                    }
                }
                Some(upload_frame::Payload::Finalize(_)) => {
                    if let Some((p, path, mut f, m, t)) = current.take() {
                        let _ = std::io::Write::flush(&mut f);
                        files.push((p, path, m, t));
                    }
                    break;
                }
                _ => {}
            }
        }

        tokio::task::spawn_blocking(move || -> arx_core::error::Result<()> {
            let mut arc = CrudArchive::open_with_crypto(&archive_path, aead_key, [0u8; 32])?;
            for (dst_path, src, mode, mtime) in files {
                arc.put_file(&src, &dst_path, mode, mtime)?;
            }
            Ok(())
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        Ok(Response::new(CrudAddResponse {
            ok: true,
            error: String::new(),
        }))
    }

    // ── CrudRm ───────────────────────────────────────────────────────────────
    async fn crud_rm(
        &self,
        request: Request<CrudRmRequest>,
    ) -> Result<Response<CrudRmResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let path = req.path.clone();
        let recursive = req.recursive;
        let _lock = self
            .archive_lock(&tenant_id, &req.archive_id)
            .lock_owned()
            .await;
        tracing::info!(tenant_id = %tenant_id, archive_id = %req.archive_id, path = %path, "crud_rm");

        tokio::task::spawn_blocking(move || -> arx_core::error::Result<()> {
            let mut arc = CrudArchive::open_with_crypto(&archive_path, aead_key, [0u8; 32])?;
            if recursive {
                arc.delete_path_recursive(&path)?
            } else {
                arc.delete_path(&path)?
            }
            Ok(())
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        Ok(Response::new(CrudRmResponse {
            ok: true,
            error: String::new(),
        }))
    }

    // ── CrudMv ───────────────────────────────────────────────────────────────
    async fn crud_mv(
        &self,
        request: Request<CrudMvRequest>,
    ) -> Result<Response<CrudMvResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let _lock = self
            .archive_lock(&tenant_id, &req.archive_id)
            .lock_owned()
            .await;
        tracing::info!(tenant_id = %tenant_id, archive_id = %req.archive_id, from = %req.from, to = %req.to, "crud_mv");

        tokio::task::spawn_blocking(move || -> arx_core::error::Result<()> {
            let mut arc = CrudArchive::open_with_crypto(&archive_path, aead_key, [0u8; 32])?;
            arc.rename(&req.from, &req.to)
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        Ok(Response::new(CrudMvResponse {
            ok: true,
            error: String::new(),
        }))
    }

    // ── CrudLs ───────────────────────────────────────────────────────────────
    async fn crud_ls(
        &self,
        request: Request<CrudLsRequest>,
    ) -> Result<Response<CrudLsResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let prefix = req.prefix.clone();
        let offset = req.offset as usize;
        let limit = req.limit as usize;

        let (entries, total_count) = tokio::task::spawn_blocking(
            move || -> arx_core::error::Result<(Vec<CrudLsEntry>, u32)> {
                let arc = CrudArchive::open_with_crypto(&archive_path, aead_key, [0u8; 32])?;
                // BTreeMap iterates in sorted path order already
                let all: Vec<CrudLsEntry> = arc
                    .index
                    .by_path
                    .iter()
                    .filter(|(p, _)| prefix.is_empty() || p.starts_with(&prefix))
                    .map(|(p, e)| CrudLsEntry {
                        path: p.clone(),
                        size: e.size,
                        mtime: e.mtime,
                    })
                    .collect();
                let total = all.len() as u32;
                let page = if limit == 0 {
                    all
                } else {
                    all.into_iter().skip(offset).take(limit).collect()
                };
                Ok((page, total))
            },
        )
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        Ok(Response::new(CrudLsResponse {
            entries,
            total_count,
        }))
    }

    // ── CrudSync ─────────────────────────────────────────────────────────────
    //
    // Compact the crud overlay in-place: the archive keeps the same ID.
    // The compacted data is written to `<data.arx>.tmp`, atomically renamed
    // over `data.arx`, and the journal/delta sidecars are cleared.
    async fn crud_sync(
        &self,
        request: Request<CrudSyncRequest>,
    ) -> Result<Response<CrudSyncResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let _lock = self
            .archive_lock(&tenant_id, &req.archive_id)
            .lock_owned()
            .await;
        tracing::info!(tenant_id = %tenant_id, archive_id = %req.archive_id, "crud_sync");
        let paths = self.store.archive_paths(&tenant_id, &req.archive_id);

        let tmp_out = paths.data.with_extension("arx.tmp");
        let archive_path_c = archive_path.clone();
        let tmp_out_c = tmp_out.clone();
        let journal_c = paths.journal.clone();
        let delta_c = paths.delta.clone();
        let seal_base = req.seal_base;

        tokio::task::spawn_blocking(move || -> arx_core::error::Result<()> {
            CrudArchive::sync_to_base(
                &archive_path_c,
                Some(&tmp_out_c),
                false,
                0.05,
                aead_key,
                [0u8; 32],
                seal_base,
            )?;
            std::fs::rename(&tmp_out_c, &archive_path_c)?;
            // Sync has committed everything into the new base — drop the overlay.
            let _ = std::fs::remove_file(&journal_c);
            let _ = std::fs::remove_file(&delta_c);
            Ok(())
        })
        .await
        .map_err(|e| Status::internal(e.to_string()))?
        .map_err(arx_err)?;

        let stats = arx_core::read::stats::compute_stats(&archive_path, aead_key).ok();
        let size_bytes = stats
            .as_ref()
            .map(|s| s.physical_bytes_base + s.physical_bytes_delta)
            .unwrap_or(0);

        Ok(Response::new(CrudSyncResponse {
            ok: true,
            size_bytes,
            stats: stats.map(crate::store::into_proto_stats),
            error: String::new(),
        }))
    }

    // ── CrudDiff ─────────────────────────────────────────────────────────────
    async fn crud_diff(
        &self,
        request: Request<CrudDiffRequest>,
    ) -> Result<Response<CrudDiffResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;

        let entries =
            tokio::task::spawn_blocking(move || -> arx_core::error::Result<Vec<CrudDiffEntry>> {
                let arc = CrudArchive::open_with_crypto(&archive_path, aead_key, [0u8; 32])?;
                Ok(arc
                    .diff()
                    .into_iter()
                    .map(|e| CrudDiffEntry {
                        kind: e.kind.to_string(),
                        path: e.path,
                    })
                    .collect())
            })
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .map_err(arx_err)?;

        Ok(Response::new(CrudDiffResponse { entries }))
    }

    // ── ChunkMap ─────────────────────────────────────────────────────────────
    async fn chunk_map(
        &self,
        request: Request<ChunkMapRequest>,
    ) -> Result<Response<ChunkMapResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let archive_path = self.store.resolve(&tenant_id, &req.archive_id)?;
        let aead_key = resolve_key(&archive_path, req.key.as_ref())?;
        let params = OpenParams {
            archive_path,
            aead_key,
            key_salt: [0u8; 32],
        };
        let repo = open_repo(Backend::Fs, params).map_err(arx_err)?;
        let rows = repo.chunk_map(&req.path).map_err(arx_err)?;
        let entries = rows
            .into_iter()
            .map(|r| ChunkMapEntry {
                ordinal: r.ordinal,
                id: r.id,
                codec: r.codec as u32,
                u_len: r.u_len,
                c_len: r.c_len,
                data_off: r.data_off,
            })
            .collect();
        Ok(Response::new(ChunkMapResponse { entries }))
    }

    // ── ListArchives ─────────────────────────────────────────────────────────
    async fn list_archives(
        &self,
        request: Request<ListArchivesReq>,
    ) -> Result<Response<ListArchivesResp>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let archives = self.store.list_archives(&tenant_id);
        Ok(Response::new(ListArchivesResp { archives }))
    }

    // ── DeleteArchive ────────────────────────────────────────────────────────
    async fn delete_archive(
        &self,
        request: Request<DeleteArchiveReq>,
    ) -> Result<Response<DeleteArchiveResp>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        self.store.delete_archive(&tenant_id, &req.archive_id)?;
        Ok(Response::new(DeleteArchiveResp {
            ok: true,
            error: String::new(),
        }))
    }

    // ── RenameArchive ────────────────────────────────────────────────────────
    async fn rename_archive(
        &self,
        request: Request<RenameArchiveRequest>,
    ) -> Result<Response<RenameArchiveResponse>, Status> {
        let tenant_id = {
            let _t = extract_bearer(&request)?;
            extract_tenant(&_t, &self.db).await?
        };
        let req = request.into_inner();
        let name = req.name.trim();
        if name.is_empty() || name.len() > 128 {
            return Ok(Response::new(RenameArchiveResponse {
                ok: false,
                error: "name must be 1..=128 chars".to_string(),
            }));
        }
        // Ownership check (also rejects path traversal).
        self.store.resolve(&tenant_id, &req.archive_id)?;
        self.store
            .write_label(&tenant_id, &req.archive_id, name)
            .map_err(|e| Status::internal(e.to_string()))?;
        Ok(Response::new(RenameArchiveResponse {
            ok: true,
            error: String::new(),
        }))
    }

    // ── Login ────────────────────────────────────────────────────────────────
    async fn login(
        &self,
        request: Request<LoginRequest>,
    ) -> Result<Response<LoginResponse>, Status> {
        let req = request.into_inner();
        let (user_id, tenant_id) = self
            .db
            .verify_login(&req.email, &req.password)
            .await
            .map_err(|e| Status::internal(e))?
            .ok_or_else(|| Status::unauthenticated("invalid email or password"))?;

        let secret = self
            .db
            .get_jwt_secret()
            .await
            .map_err(|e| Status::internal(e))?;
        let access_token = issue_jwt(&user_id, &tenant_id, &secret)?;
        let refresh_token = self
            .db
            .create_refresh_token(&user_id, &tenant_id)
            .await
            .map_err(|e| Status::internal(e))?;

        Ok(Response::new(LoginResponse {
            access_token,
            refresh_token,
            expires_in: 900,
            error: String::new(),
        }))
    }

    // ── RefreshToken ─────────────────────────────────────────────────────────
    async fn refresh_token(
        &self,
        request: Request<RefreshTokenRequest>,
    ) -> Result<Response<RefreshTokenResponse>, Status> {
        let req = request.into_inner();
        let (user_id, tenant_id) = self
            .db
            .consume_refresh_token(&req.refresh_token)
            .await
            .map_err(|e| Status::internal(e))?
            .ok_or_else(|| Status::unauthenticated("invalid or expired refresh token"))?;

        let secret = self
            .db
            .get_jwt_secret()
            .await
            .map_err(|e| Status::internal(e))?;
        let access_token = issue_jwt(&user_id, &tenant_id, &secret)?;
        let new_refresh_token = self
            .db
            .create_refresh_token(&user_id, &tenant_id)
            .await
            .map_err(|e| Status::internal(e))?;

        Ok(Response::new(RefreshTokenResponse {
            access_token,
            new_refresh_token,
            expires_in: 900,
            error: String::new(),
        }))
    }

    // ── Logout ───────────────────────────────────────────────────────────────
    async fn logout(
        &self,
        request: Request<LogoutRequest>,
    ) -> Result<Response<LogoutResponse>, Status> {
        let req = request.into_inner();
        self.db
            .revoke_refresh_token(&req.refresh_token)
            .await
            .map_err(|e| Status::internal(e))?;
        Ok(Response::new(LogoutResponse {
            ok: true,
            error: String::new(),
        }))
    }

    // ── Whoami ───────────────────────────────────────────────────────────────
    async fn whoami(
        &self,
        request: Request<WhoamiRequest>,
    ) -> Result<Response<WhoamiResponse>, Status> {
        let (tenant_id, user_id) = {
            let _t = extract_bearer(&request)?;
            extract_identity(&_t, &self.db).await?
        };
        let (email, _) = self
            .db
            .get_user_info(&user_id)
            .await
            .map_err(|e| Status::internal(e))?
            .ok_or_else(|| Status::not_found("user not found"))?;
        Ok(Response::new(WhoamiResponse {
            user_id,
            email,
            tenant_id,
        }))
    }

    // ── CreateTenant (admin) ──────────────────────────────────────────────────
    async fn create_tenant(
        &self,
        request: Request<CreateTenantRequest>,
    ) -> Result<Response<CreateTenantResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let name = request.into_inner().name;
        match self.db.create_tenant(&name).await {
            Ok(id) => Ok(Response::new(CreateTenantResponse {
                tenant_id: id,
                error: String::new(),
            })),
            Err(e) => Ok(Response::new(CreateTenantResponse {
                tenant_id: String::new(),
                error: e,
            })),
        }
    }

    // ── CreateUser (admin) ────────────────────────────────────────────────────
    async fn create_user(
        &self,
        request: Request<CreateUserRequest>,
    ) -> Result<Response<CreateUserResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let req = request.into_inner();
        match self
            .db
            .create_user(&req.tenant_id, &req.email, &req.password)
            .await
        {
            Ok(id) => Ok(Response::new(CreateUserResponse {
                user_id: id,
                error: String::new(),
            })),
            Err(e) => Ok(Response::new(CreateUserResponse {
                user_id: String::new(),
                error: e,
            })),
        }
    }

    // ── CreateApiKey (admin) ──────────────────────────────────────────────────
    async fn create_api_key(
        &self,
        request: Request<CreateApiKeyRequest>,
    ) -> Result<Response<CreateApiKeyResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let req = request.into_inner();
        // Resolve user's tenant_id from the DB
        let (_, tenant_id) = self
            .db
            .get_user_info(&req.user_id)
            .await
            .map_err(|e| Status::internal(e))?
            .ok_or_else(|| Status::not_found("user not found"))?;
        let expires_at = if req.expires_in_secs == 0 {
            None
        } else {
            Some(
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_secs() as i64
                    + req.expires_in_secs as i64,
            )
        };
        match self
            .db
            .create_api_key(&req.user_id, &tenant_id, &req.name, expires_at)
            .await
        {
            Ok(key) => Ok(Response::new(CreateApiKeyResponse {
                api_key: key,
                error: String::new(),
            })),
            Err(e) => Ok(Response::new(CreateApiKeyResponse {
                api_key: String::new(),
                error: e,
            })),
        }
    }

    // ── RevokeApiKey (admin) ──────────────────────────────────────────────────
    async fn revoke_api_key(
        &self,
        request: Request<RevokeApiKeyRequest>,
    ) -> Result<Response<RevokeApiKeyResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let key_hash = request.into_inner().key_hash;
        match self.db.revoke_api_key(&key_hash).await {
            Ok(()) => Ok(Response::new(RevokeApiKeyResponse {
                ok: true,
                error: String::new(),
            })),
            Err(e) => Ok(Response::new(RevokeApiKeyResponse {
                ok: false,
                error: e,
            })),
        }
    }

    // ── ListTenants (admin) ───────────────────────────────────────────────────
    async fn list_tenants(
        &self,
        request: Request<ListTenantsRequest>,
    ) -> Result<Response<ListTenantsResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let tenants = self
            .db
            .list_tenants()
            .await
            .map_err(|e| Status::internal(e))?
            .into_iter()
            .map(|t| TenantInfoMsg {
                id: t.id,
                name: t.name,
                created_at: t.created_at,
            })
            .collect();
        Ok(Response::new(ListTenantsResponse { tenants }))
    }

    // ── ListUsers (admin) ─────────────────────────────────────────────────────
    async fn list_users(
        &self,
        request: Request<ListUsersRequest>,
    ) -> Result<Response<ListUsersResponse>, Status> {
        check_admin(&request, &self.admin_key)?;
        let tenant_id = request.into_inner().tenant_id;
        let users = self
            .db
            .list_users(&tenant_id)
            .await
            .map_err(|e| Status::internal(e))?
            .into_iter()
            .map(|u| UserInfoMsg {
                id: u.id,
                email: u.email,
                tenant_id: u.tenant_id,
                active: u.active,
                created_at: u.created_at,
            })
            .collect();
        Ok(Response::new(ListUsersResponse { users }))
    }
}
