[package]
name = "arx-core"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
ciborium = "0.2.2"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
time = "0.3.43"
walkdir = "2.5.0"
